### PR TITLE
Add ktlint

### PR DESCRIPTION
**Pull request by will-hou**
Code written by @codingvic . He had to leave before he got a chance to push so I did it on my account.

Draft PR for now because I'm going to try and bump the ktlint version, and because the `Constants.kt` file needs more objects before ktlint is happy

### CODE REVIEW

**Comment by mckelveygreg** [comment]
If we feel like it, we can add a ktlint badge to the readme!
`[ktlint](https://ktlint.github.io/)`

**Comment by mckelveygreg** [comment]
We can add a `gitPreCommitHook` to make sure that something won't be committed unless it passes linting! 
```
# install git hook to automatically check files for style violations on commit
# Run "ktlint installGitPrePushHook" if you wish to run ktlint on push instead
$ ktlint installGitPreCommitHook
```
reference: https://github.com/pinterest/ktlint#usage

**Comment by mckelveygreg** [comment]
so I thoguht this would be more straight forward... Check out my #14 pr and make it better :)

**Comment by will-hou** [comment]
Not sure why github is saying 14 files were changed... Should just be 2.

@codingvic probably going to try and get this merged today but you should definitely check out what was changed when you get back from your trip

**Comment by will-hou** [comment]
See #14

**Pull request closed without merging**
